server:
  port: 8080

greeting: "Hello Local!"

spring:
  application:
    name: greeting-service
  config:
    import: configserver:http://localhost:8888/
  cloud:
    config:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh

